### ISSUE TITLE
Imported GLSL shaders are unsupported by the configuration

### ISSUE THREAD

**Issue by AxiomeCG** [mayacoda/simple-threejs-typescript-starter#1]
# Problem
I wanted to confirm that you had the same problem than me while configuring Typescript and ThreeJS
I tried to import a GLSL shader in the `example.ts`.

Typescript complained about the module path. So I added the following quick fix in the shader folder: 

**glsl.d.ts**
```typescript
declare module "*.glsl" {
  const value: string;
  export default value;
}
```
No complaint in the Typescript anymore, but now the app is crashing with the following error :
![image](https://user-images.githubusercontent.com/18304870/176777102-45ad2de2-bb5b-4e3b-9869-17b7b7c69aad.png)
![image](https://user-images.githubusercontent.com/18304870/176777552-92216638-3f2b-4e19-8904-38f8e8d30fba.png)
![image](https://user-images.githubusercontent.com/18304870/176777626-2eee405b-9899-4355-a26e-564b695a52af.png)

# Possible Solution

I don't know ViteJS, but I think it is like Parcel, or webpack, you need to add a specific loader for GLSL files like 
https://www.npmjs.com/package/vite-plugin-glsl

**Comment by mayacoda** [comment]
Thanks so much for looking into this and solving it the issue! I just have one question about the `#version` directive in the shaders (in the PR), but otherwise I think #2 can be merged. 🎉
