### ISSUE TITLE
Incredible Work

### ISSUE THREAD

**Issue by timhuff** [mayacoda/simple-threejs-typescript-starter#4]
Calling this library a "starter" doesn't do it justice. This thing has everything you need. I've found that it works particularly well with the `animejs` library. Example:

```ts
  init() {
    this.initEnvironment()

    const sphere = new Sphere()
    sphere.castShadow = true
    sphere.position.set(0, 0, 0)

    this.engine.scene.add(sphere)

    this.engine.debug.gui.add(sphere.position, 'y', 0, 2, 0.1).name('box y').listen();

    anime({
      targets: sphere.position,
      y: 2,
      duration: 3000,
      loop: true,
      easing: function (_el, _i, _total) {
        return function (t) {
          return (1 - Math.cos(2 * Math.PI * t)) / 2;
        }
      }
    })
  }
```

That code animates the sphere as oscillating up and down and binds to the `y` property of `sphere.position`, same as `lil-gui` does. The `.listen()` call causes the GUI's slider to animate as well. The `update` function remains empty.

**Comment by mayacoda** [comment]
@timhuff Thank you so much for your kind words, it really made my week 💕 

Let me know if you would like to see any features developed or if anything doesn't behave as you expect.
